### ISSUE TITLE
Proxy Settings are not supported

### ISSUE THREAD

**Issue by josh-barker** [criteo-cookbooks/nexus3#12]
Hi, I'm running test kitchen in an environment that does not have direct connectivity to the internet.

I've found that `download_url` fails:

Kitchen Output:

```
============================================================
Error executing action `install` on resource 'nexus3[nexus]'
============================================================
Net::OpenTimeout
----------------
execution expired

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:13:in `download_url'
/tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:54:in `block in class_from_file'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/nexus3/recipes/default.rb

1: nexus3 'nexus' do
2:   action :install
3: end
```

**Comment by olive42** [comment]
Thank you for reporting this. The way Nexus3 is downloaded right now is not quite Chef-like and we would like to rewrite this by using the remote_file Chef resource, which should honor proxy settings.

I assume you set proxy settings somewhere, let us know how you set them?

**Comment by josh-barker** [comment]
Hi @olive42, thanks for the quick reply.
I actually had to replace the `download_url` method so that it just returned the url.
It is possible to pass proxy settings into HTTP::NET.new, but the way that its implemented at the moment doesn't allow it.
See https://github.com/criteo-cookbooks/nexus3/blob/master/providers/default.rb#L13

From what I can see, the method ensures that a version is retrieved, so that folders are created including the version.

An alternative implementation could require the precise url including the version, which means we could remove the `download_url` method.

**Comment by dhoer** [comment]
Here is a PR that uses Chef::HTTP that inherits Chef's proxy behavior: https://github.com/dhoer/chef-chromedriver/pull/7/files#diff-55bf87238c9b8af164c5133a60721f12R16

I think this approach will support proxies and allow for version to be part of the download.

**Comment by olive42** [comment]
Hi Josh,
The latest release now supports installing nexus as a resource. download_url returns a url and we rely on the ark cookbook to download and install nexus3.

From a quick check, you can either use the standard HTTP_PROXY environment variable, or update your client.rb file for the same. Hope this helps!

**Comment by josh-barker** [comment]
Hi @olive42 Thanks for letting me know. Unfortunately, I still get the error.

I'm using version `2.1.1` of the cookbook.

https://github.com/criteo-cookbooks/nexus3/blob/v2.1.0/providers/default.rb#L54

```
 * nexus3[nexus] action install[2017-09-11T16:33:48+10:00] INFO: Processing nexus3[nexus] action install (ibm_nexus::install line 25)
       
           
           ==================================
           Error executing action `install` on resource 'nexus3[nexus]'
           ==================================
           
           Net::OpenTimeout
           ----------------
           execution expired
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:14:in `download_url'
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:55:in `block in class_from_file'
```

**Comment by Superbasil3** [comment]
Hi everybody,
I have the same issue with the proxy configuration for the version 2.1.1.

I have proxy set on my linux environnent and in client.rb file.

Do you have any work-arround before a fix ? 

` * nexus3[nexus] action install                                                                      
                                                                                                     
   ================================================================================                  
   Error executing action `install` on resource 'nexus3[nexus]'                                      
   ================================================================================                  
                                                                                                     
   Net::OpenTimeout                                                                                  
   ----------------                                                                                  
   execution expired                                                                                 
                                                                                                     
   Cookbook Trace:                                                                                   
   ---------------                                                                                   
   /var/chef/cache/cookbooks/nexus3/providers/default.rb:14:in `download_url'                        
   /var/chef/cache/cookbooks/nexus3/providers/default.rb:55:in `block in class_from_file'            `

**Comment by jujugrrr** [comment]
hi,
since version 3.0.0 has been released, download_url doesn't do this Net::Http.start anymore some it should have solved the issue

**Comment by Annih** [comment]
@josh-barker have you been able to test the version 3.0.0? Could you confirm it solved your issue?

**Comment by josh-barker** [comment]
Hi @Annih I haven't had a chance yet. Will let you know after I've checked it.

**Comment by josh-barker** [comment]
Hi @Annih I've just tested with `3.0.0` and the proxy settings are working.

Thanks!
