### ISSUE TITLE
Cookbook in supermarket

### ISSUE THREAD

**Issue by gfrntz** [criteo-cookbooks/nexus3#24]
Hello,
This cookbook in chef supermarket doesn't contains repo resource.

**Comment by olive42** [comment]
Hi,
I am not sure I understand; the resource is named 'nexus3_repo'. You can use it in a recipe:

nexus3_repo 'myrepo' do
  repo_type 'maven2-hosted'
end

It is documented in https://github.com/criteo-cookbooks/nexus3#nexus3_repo but it is likely this section needs a better example.

**Comment by Annih** [comment]
Hello @gfrntz

I think I understand your issue. We didn't release the new version to the supermarket because we still need to test it a bit more.

Please be patient we'll do our best to release it soon.

Thanks!

**Comment by pvandervelde** [comment]
@Annih Any progress on the testing. Would love to be able to use the nexus3_repo resource

**Comment by jmauro** [comment]
Hello @pvandervelde,

The cookbook has been published to the supermarket.

Regards,
JM
