### ISSUE TITLE
Doesn't complete downloading the tar.gz

### ISSUE THREAD

**Issue by budgester** [criteo-cookbooks/nexus3#26]
Recipe: nexus3::default
         * nexus3[nexus] action install[2017-07-31T10:22:14+00:00] INFO: Processing nexus3[nexus] action install (nexus3::default line 1)

           ================================================================================
           Error executing action `install` on resource 'nexus3[nexus]'
           ================================================================================

           SystemStackError
           ----------------
           stack level too deep

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:13:in `block in download_url'
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:13:in `download_url'
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:20:in `download_url'
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:20:in `download_url'
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:20:in `download_url'
           /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:20:in `download_url'
.
.
.
         /tmp/kitchen/cache/cookbooks/nexus3/providers/default.rb:54:in `block in class_from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/nexus3/recipes/default.rb

             1: nexus3 'nexus' do
             2:   action :install
             3: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/nexus3/recipes/default.rb:1:in `from_file'

           nexus3("nexus") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :nexus3
             cookbook_name "nexus3"
             recipe_name "default"
             url "http://download.sonatype.com/nexus/3/latest-unix.tar.gz"
             servicename "nexus"
             path "/opt"
             data "/opt/sonatype-work/nexus3"
             home "/opt/nexus3"
             properties_cookbook "nexus3"
             properties_source "nexus.properties.erb"
             properties_variables {"host"=>"0.0.0.0", "port"=>"8081", "args"=>"${jetty.etc}/jetty.xml,${jetty.etc}/jetty-http.xml,${jetty.etc}/jetty-requestlog.xml", "context_path"=>"/"}
             vmoptions_cookbook "nexus3"
             vmoptions_source "nexus.vmoptions.erb"
             vmoptions_variables {"Xms"=>"1200M", "Xmx"=>"1200M"}
           end

**Comment by budgester** [comment]
Using nexus3 version 2.1.0 as released on chef supermarket.

**Comment by f1yers** [comment]
@budgester - I was having the same issue too until I updated the url.
```default['nexus3']['url'] = 'http://download.sonatype.com/nexus/3/nexus-3.4.0-02-unix.tar.gz'```

**Comment by chris-gillatt** [comment]
@budgester Yeah it looks like there's been a new version of Nexus released over the last couple of days (3.5.0-02) which for some reason this cookbook does not like installing.  @f1yers solution works fine until someone fixes it 👍

**Comment by chris-gillatt** [comment]
For the latest version, use:
`default['nexus3']['url'] = 'http://download.sonatype.com/nexus/3/nexus-3.5.0-02-unix.tar.gz'`

**Comment by olive42** [comment]
This will be fixed when https://github.com/criteo-cookbooks/nexus3/pull/25 is merged, which basically will force you to specify the URL of the archive you want to install.

**Comment by jmauro** [comment]
This issue has been merged.
