### ISSUE TITLE
Setting & applying nexus file limits with systemd

### ISSUE THREAD

**Issue by chris-gillatt** [criteo-cookbooks/nexus3#27]
On version 3.5.0 of Nexus, there's a warning in the GUI which suggests changing the default file handlers to 65536.  What's the best method to define file limits for nexus with systemd?
Systemd does not support /etc/security/limits.conf, which was my first idea, and using the limits cookbook (https://supermarket.chef.io/cookbooks/limits) was my second.  Unfortunately systemd has already started by the time of the nexus un-tar, meaning any new values you've passed will not be picked up (either overwritten or ignored depending on scenario).
How do we set the limits in nexus.service file which the nexus3 cookbook creates?

You can test to see if your changes are affective by adding `echo 'ulimit -a | grep "open files"'` to line 512 of `/opt/nexus3/bin/nexus` and checking `/var/log/messages` (or syslog depending on distro).  I'm on Centos 7.3.

**Comment by olive42** [comment]
the limits cookbook only changes /etc/security/limits.conf. You need to update the systemd service file (this will be defined in https://github.com/criteo-cookbooks/nexus3/pull/25/files#diff-1baa1dc1e3b9e00172a5011e8aaa4ea8 when this is merged), by setting LimixNOFILE=65536 in the [Exec] section of the service file.

**Comment by lehn-etracker** [comment]
Same problem here. Hope to see updated version soon.

**Comment by lehn-etracker** [comment]
you could replace your template for systemd unit with native chef systemd_unit like this.

`# nexus 3.5 needs higher ulimit for max open files
systemd_unit 'nexus.service' do
  content(
    Unit: {
      Description: 'nexus service',
      Documentation: 'https://help.sonatype.com/display/NXRM3',
      After: 'network.target'
    },
    Service: {
      Type: 'forking',
      ExecStart: '/opt/nexus3/bin/nexus start',
      ExecStop: '/opt/nexus3/bin/nexus stop',
      LimitNOFILE: 65_536,
      User: 'nexus',
      Restart: 'on-abort'
    },
    Install: {
      WantedBy: 'multi-user.target'
    }
  )
  action %i[create enable]
end`

**Comment by chris-gillatt** [comment]
This is the solution I used to tackled it, with intention to revise or remove it once the new version was merged.  Essentially I delete the service file and recreate it with the new values before the service starts. 

```
systemd_service 'nexus' do
  action :delete
end

# Configures a new systemd service
# limit configuration required for extra
# file handles, and to replace nexus.service
systemd_service 'nexus' do
  action :create
  description 'Nexus dependancy repo manager'
  install do
    wanted_by 'multi-user.target'
  end
  service do
    type 'forking'
    user 'nexus'
    group 'nexus'
    limit_nofile 65_536
    limit_nproc 65_536
    exec_start '/opt/nexus3/bin/nexus start'
    exec_stop '/opt/nexus3/bin/nexus stop'
  end
end
```

**Comment by olive42** [comment]
@chris-gillatt I have a PR open to replace the systemd template with using the systemd cookbook, but I did not have time to make it work yet. What you suggest is great, and perhaps the number of open files can be read from an attribute.
