### ISSUE TITLE
Property name collision

### ISSUE THREAD

**Issue by szeraf** [criteo-cookbooks/nexus3#31]
Hello guys!
I tried to initialize a new repo using the nexus3_api resource, and got the following error:

```
null_resource.nexus (chef): Deprecated features used!
null_resource.nexus (chef):   Property `ignore_failure` of resource `nexus3_api` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
null_resource.nexus (chef):     - /var/chef/cache/cookbooks/nexus3/resources/api.rb:14:in 'class_from_file'
null_resource.nexus (chef):    See https://docs.chef.io/deprecations_property_name_collision.html for further details.
null_resource.nexus (chef):   Property `sensitive` of resource `nexus3_api` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
null_resource.nexus (chef):     - /var/chef/cache/cookbooks/nexus3/resources/api.rb:17:in 'class_from_file'
null_resource.nexus (chef):    See https://docs.chef.io/deprecations_property_name_collision.html for further details.
```

Is it a known issue, or am I using something wrong?
The recipe looks like this:
```
nexus3 'nexus' do
  action :install
end

nexus3_api 'maven-internal' do
  content "repository.createMavenHosted('maven-internal')"
  action :run
end
```

Chef: 12.19.36

**Comment by olive42** [comment]
Which version of the cookbook do you use? I removed the `ignore_failure` attribute during the api resource rewrite in https://github.com/criteo-cookbooks/nexus3/commit/903a125f4c23c12f24cce2def9bb6c28885603e5#diff-d4e072c98ae66c01080742a73c774588

If you pull version 2.1.1 from the Supermarket, you should have it. We still need to change the link URL pointing to sources.

**Comment by szeraf** [comment]
Thanks, I think the cookbook version is 2.1.0, I'll definitely try the mentioned version.

**Comment by szeraf** [comment]
That solved the issue, thank you!
