### ISSUE TITLE
FYI, I put up all of my cookbooks up for adoption

### ISSUE THREAD

**Issue by dhoer** [criteo-cookbooks/nexus3#40]
I know this isn't probably the correct place for this announcement, but I know you have mentioned interest in adopting some of the other cookbook I maintained.

https://github.com/dhoer?utf8=%E2%9C%93&tab=repositories&q=chef&type=&language=

**Comment by Annih** [comment]
Thanks for the information Dennis, and many thanks for having provided all these cookbooks ^^
We'll continue working with nexus3 & nssm, hopefully the community will support the rest of your cookbooks.
