### ISSUE TITLE
Please release a patch version

### ISSUE THREAD

**Issue by xtimon** [criteo-cookbooks/nexus3#46]
The commit is pretty valuable, please release the commit as a patch version:
https://github.com/criteo-cookbooks/nexus3/pull/39/commits

**Comment by olive42** [comment]
This has been released to the master branch. We plan to make a major release when we finish adding support for tasks. I will ask around if we can do a patch release for this.

**Comment by jmauro** [comment]
Hello,

We release a mid-major release in order to push out all the bugfix we did.

**Comment by eheydrick** [comment]
Thanks for the release. Can you update the CHANGELOG too.
