### ISSUE TITLE
Default API endpoint updated in 3.8.x

### ISSUE THREAD

**Issue by mynamewastaken** [criteo-cookbooks/nexus3#55]
The "/service/siesta/rest/v1/script" endpoint has been moved to "/service/rest/v1/script".

https://help.sonatype.com/display/NXRM3/2018+Release+Notes#id-2018ReleaseNotes-1RepositoryManager3.8.0

**Comment by jmauro** [comment]
There is PR to update nexus to the latest version: https://github.com/criteo-cookbooks/nexus3/pull/54
