### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by pvandervelde** [criteo-cookbooks/nexus3#62]
It would be nice to have the current changes rolled up into a new version. Many new features and bug fixes have been released which I would love to use (e.g. #44, #36 and the update to use 3.8 by default).

**Comment by olive42** [comment]
We are thinking about it, since we now have all the features we want.

**Comment by fletchowns** [comment]
@olive42 any word on when the new version will be released?

**Comment by josh-barker** [comment]
@olive42 @Annih any news on the next release?

**Comment by jmauro** [comment]
Hello @josh-barker,

I hope we will it soon (optimistically this week) 

Regards, 
JM

**Comment by jmauro** [comment]
Hello @josh-barker,

The cookbook has been released


Regards,
JM
