### ISSUE TITLE
Deprecated features use

### ISSUE THREAD

**Issue by dkder3k** [criteo-cookbooks/nexus3#70]
When using nexus3_api resource I get this message:
```Deprecated features used!
rename api_client to new_resource.api_client at 1 location:
  - /var/chef/cache/cookbooks/nexus3/resources/api.rb:21:in `block (2 levels) in class_from_file'
See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
rename api_client to current_resource.api_client at 1 location:
  - /var/chef/cache/cookbooks/nexus3/resources/api.rb:30:in `block (2 levels) in class_from_file'
See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
```
At the moment all works fine, but according to [this page](https://docs.chef.io/deprecations_namespace_collisions.html) in Chef 14 this functionality will be removed

**Comment by Annih** [comment]
Hello @dkder3k 
Thanks for reporting this issue, we were aware of the breaking change for Chef 14 but completely forgot to patch *nexus3* accordingly!
I'm working on a patch right now :)

**Comment by dkder3k** [comment]
@Annih thanks for all your work :)
