### ISSUE TITLE
Default property api_client is not evaluated using lazy

### ISSUE THREAD

**Issue by josh-barker** [criteo-cookbooks/nexus3#72]
The default value for the `api` resource  is `default: lazy { ::Nexus3::Api.default(node) }`
https://github.com/criteo-cookbooks/nexus3/blob/master/resources/api.rb#L4

However, the other resources have `default: ::Nexus3::Api.default(node)`
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/repo.rb#L5
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/group.rb#L6
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/role.rb#L5
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/task.rb#L4
- https://github.com/criteo-cookbooks/nexus3/blob/master/resources/user.rb#L7

I found that in the same chef run, this caused unexpected results.

```ruby
nexus3 'nexus' do
  action :install

  notifies :create, 'nexus3_api[admin_change_password]', :immediately
  notifies :run, 'nexus3_api[admin_change_password]', :immediately
  notifies :delete, 'nexus3_api[admin_change_password]', :immediately
end

nexus3_api 'admin_change_password' do
  script_name 'admin_change_password'
  content   "security.securitySystem.changePassword('admin', args)"
  args      'some new password'
  sensitive true

  action :nothing
end

ruby_block 'update nexus api credentials' do
  block do
    # this is run at converge time so that following resources use the new password
    node.override['nexus3']['api']['password'] = 'some new password'
  end
  action :run
end

nexus3_repo "Create a repo" do
  repo_name 'new-repo'
  repo_type 'raw-hosted'
  # without this, it would fail
  api_client lazy { ::Nexus3::Api.default(node) }

  action :create
end
```

**Comment by jmauro** [comment]
Hello @josh-barker,

You are right we are not very consistent on our resource definition, we'll try to fix that and let you when it is done. Do that make sense?


Regards,
JM
