### ISSUE TITLE
Replace localhost to host's active ip address

### ISSUE THREAD

**Issue by Edvecs** [criteo-cookbooks/nexus3#78]
**Issue:** localhost is hardcoded at the default nexus3 api endpoint:
default['nexus3']['api']['endpoint'] = 'http://localhost:8081/service/rest/v1/script/'

localhost does not resolve always well (ipv4 vs ipv6 configuration could cause an error) but the active ip address will always work.

**Proposed Solution**:
Use this as the default variable: default['nexus3']['api']['endpoint'] = "http://#{node['ipaddress']}:8081/service/rest/v1/script/"

**Comment by jmauro** [comment]
Hello @Edvecs,

The all point of creating the attributes `default['nexus3']['api']['endpoint']` is basically to provide any user to set the endpoint he wants so feel free to update this attribute the way you want.

The default settings is to answer the most common case but you can do as you wish in a wrapper cookbook, does that resolve your issue?

Regards,
JM

**Comment by Edvecs** [comment]
Thanks. I will do that then.
