### ISSUE TITLE
Default password admin123 no longer works with Nexus 3.17.0

### ISSUE THREAD

**Issue by fletchowns** [criteo-cookbooks/nexus3#98]
Ran into this one trying to upgrade to the latest Nexus 3.17.0 release.

Nexus now generates UUID for the default password and puts it in `/opt/sonatype-work/nexus3/admin.password`. This cookbook assumes the default password is admin123, which no longer works as of this new nexus version.

Found this mentioned in the [release notes](https://help.sonatype.com/repomanager3/release-notes/2019-release-notes): 
> In new instances the admin user will now start with a randomly generated password.

I used the following as a workaround:
```ruby
ruby_block 'read random nexus password into attribute' do
  block do
    node.override['nexus3']['api']['password'] = File.read("#{node['nexus3']['data']}/admin.password")
  end
  action :run
end
```

**Comment by pvandervelde** [comment]
@fletchowns Do you need to wait for Nexus to start and write to the password file? I've added your work around directly after installing nexus (which should start the service) but it's picking up the default password (`admin123`) instead of the new one.

**Comment by fletchowns** [comment]
@pvandervelde yes I think that may have been the case when I applied the workaround, it was likely after the initial converge I ran which installed nexus. So you may need to wait for the service to start before the file exists. Hope this helps!

**Comment by pvandervelde** [comment]
@fletchowns Yeah I got it to update I think after waiting for the file to appear, but when I try printing the value that is in the attribute I still get the old value. I guess I'm being tripped up by a Chef behaviour there.
Also my next call to the Nexus API fails for some reason eventhough it seems to be using the right password .. sigh

**Comment by sumanthk-vha** [comment]
@pvandervelde I'm facing the same issue. Although I override the default password after the service starts, Nexus API call fails with 401 error(unauthorized) error. I was wondering if you had found a solution/workaround. Thanks.

**Comment by pvandervelde** [comment]
@sumanthk-vha I've gotten it to work by doing this:

    nexus_instance_name = node['nexus3']['instance_name']
    nexus3 nexus_instance_name do
      action :install
      nexus3_group node['nexus3']['service_group']
      nexus3_user node['nexus3']['service_user']
    end

    # Since Nexus 3.17.0 the default admin password is generated, so we need to get
    # the actual password before we do something useful
    # See: https://github.com/criteo-cookbooks/nexus3/issues/98
    #
    # It may take a while for Nexus to start and write the password file so we hang around
    # for a little while to ensure that the file exists
    ruby_block 'wait for nexus password file' do
      block do
        true until ::File.exist?("#{node['nexus3']['data']}/admin.password")
      end
    end

    ruby_block 'read random nexus password into attribute' do
      block do
        node.override['nexus3']['api']['password'] = File.read("#{node['nexus3']['data']}/admin.password")
      end
      action :run
    end

    log 'Nexus generated password' do
      level :warn
      message "Nexus generated password: #{node['nexus3']['api']['password']}"
    end

    # Rename the password file chef generated to trick Nexus into thinking that everything is ok
    ruby_block 'rename nexus password file' do
      block do
        ::File.rename("#{node['nexus3']['data']}/admin.password", "#{node['nexus3']['data']}/admin.generated.password")
      end
      not_if { File.exist?("#{node['nexus3']['data']}/admin.generated.password") }
    end

The log statement doesn't print out the actual password but I don't understand why. However the actual password is saved so all my API calls work

**Comment by jeremy-clerc** [comment]
Thanks for the report and the workaround, fyi, another approach is to update the password to one you know (the attribute, so admin123 by default), so if you need to access the UI for example, you do not have to go look on the machine the password, you already know it.

https://github.com/criteo-cookbooks/nexus3/blob/master/test/fixtures/cookbooks/nexus3_test/recipes/change_admin_password.rb

Closing this issue.
